/*******************************************************************************
 * Copyright (c) 2025 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 * Copyright (c) 2026 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 * AI Disclosure: This file was partially AI-generated.
 * AI-Generated by: GitHub Copilot. The AI-generated portions are made
 * available under CC0-1.0 and not subject to the project's licence.
 * The human contributor has reviewed and verified that the code is correct.
 *
 * SPDX-License-Identifier: Apache-2.0 AND CC0-1.0
 * Assisted-by: GitHub Copilot (claude-sonnet-4-5)
 ******************************************************************************/

package docs

import (
	"fmt"
	"os"
	"path"
	"testing"
)

func TestPassIfAnyMarkdownFileIsPresent(t *testing.T) {
	dir := t.TempDir()
	filePath := path.Join(dir, "docs", "admin", "README.md")

	err := os.MkdirAll(path.Dir(filePath), os.ModePerm)
	if err != nil {
		t.Fatalf("failed to create directories: %v", err)
	}

	fmt.Printf("%s\n", filePath)
	_, err = os.Create(filePath)
	if err != nil {
		t.Fatalf("failed to create file: %v", err)
	}

	fmt.Printf("%s\n", filePath)
	_, _ = os.Create(filePath)

	result := NewAdminGuideExists(dir).Test()

	if !result.Passed {
		t.Error("Admin Guide is not in directory")
	}
}

func TestFailIfMarkdownFileIsMissing(t *testing.T) {
	dir := t.TempDir()
	filePath := path.Join(dir, "docs", "admin", "README.txt")
	err := os.MkdirAll(path.Dir(filePath), os.ModePerm)
	if err != nil {
		t.Fatalf("failed to create directories: %v", err)
	}

	fmt.Printf("%s\n", filePath)
	_, err = os.Create(filePath)
	if err != nil {
		t.Fatalf("failed to create file: %v", err)
	}

	fmt.Printf("%s\n", filePath)
	_, _ = os.Create(filePath)

	result := NewAdminGuideExists(dir).Test()

	if result.Passed {
		t.Error("AdminGuideExists should fail if no Markdown is present in docs/admin.")
	}
}

func TestProvidesErrorDescriptionIfFailing(t *testing.T) {
	result := NewChangelogExists("./").Test()

	if result.ErrorDescription == "" {
		t.Errorf("Failing tests should provide an error description")
	}
}

func TestPassWithConfiguredAdminGuidePath(t *testing.T) {
	dir := t.TempDir()

	// Create a file at a custom path
	customPath := path.Join(dir, "docs", "operations", "admin.md")
	err := os.MkdirAll(path.Dir(customPath), os.ModePerm)
	if err != nil {
		t.Fatalf("failed to create directories: %v", err)
	}
	_, err = os.Create(customPath)
	if err != nil {
		t.Fatalf("failed to create file: %v", err)
	}

	// Write .tractusx with adminGuideEntryPath configured
	tractusx := path.Join(dir, ".tractusx")
	err = os.WriteFile(tractusx, []byte("configureReleaseChecks:\n  adminGuideEntryPath: docs/operations/*.md\n"), 0644)
	if err != nil {
		t.Fatalf("failed to write .tractusx: %v", err)
	}

	result := NewAdminGuideExists(dir).Test()

	if !result.Passed {
		t.Errorf("Expected pass when configured path matches, got error: %s", result.ErrorDescription)
	}
}

func TestFailWhenNeitherDefaultNorConfiguredPathMatches(t *testing.T) {
	dir := t.TempDir()

	// Write .tractusx with adminGuideEntryPath that does not match any file
	tractusx := path.Join(dir, ".tractusx")
	err := os.WriteFile(tractusx, []byte("configureReleaseChecks:\n  adminGuideEntryPath: docs/nonexistent/*.md\n"), 0644)
	if err != nil {
		t.Fatalf("failed to write .tractusx: %v", err)
	}

	result := NewAdminGuideExists(dir).Test()

	if result.Passed {
		t.Error("Expected failure when neither default nor configured path has markdown files")
	}
}

func TestFallbackToDefaultWhenTractusxMissing(t *testing.T) {
	dir := t.TempDir()

	// No .tractusx file — create default docs/admin/*.md
	defaultPath := path.Join(dir, "docs", "admin", "guide.md")
	err := os.MkdirAll(path.Dir(defaultPath), os.ModePerm)
	if err != nil {
		t.Fatalf("failed to create directories: %v", err)
	}
	_, err = os.Create(defaultPath)
	if err != nil {
		t.Fatalf("failed to create file: %v", err)
	}

	result := NewAdminGuideExists(dir).Test()

	if !result.Passed {
		t.Errorf("Expected pass with default path when .tractusx is missing, got error: %s", result.ErrorDescription)
	}
}

func TestFallbackToDefaultWhenConfigureReleaseChecksEmpty(t *testing.T) {
	dir := t.TempDir()

	// .tractusx without adminGuideEntryPath
	tractusx := path.Join(dir, ".tractusx")
	err := os.WriteFile(tractusx, []byte("repoCategory: product\n"), 0644)
	if err != nil {
		t.Fatalf("failed to write .tractusx: %v", err)
	}

	// Create default docs/admin/*.md
	defaultPath := path.Join(dir, "docs", "admin", "guide.md")
	err = os.MkdirAll(path.Dir(defaultPath), os.ModePerm)
	if err != nil {
		t.Fatalf("failed to create directories: %v", err)
	}
	_, err = os.Create(defaultPath)
	if err != nil {
		t.Fatalf("failed to create file: %v", err)
	}

	result := NewAdminGuideExists(dir).Test()

	if !result.Passed {
		t.Errorf("Expected pass with default path when adminGuideEntryPath is not configured, got error: %s", result.ErrorDescription)
	}
}
